### ISSUE TITLE
При суммировании игрового времени игроков в методе getSumPlayedTime возвращается ноль

### ISSUE THREAD

**Issue by 7Yuliya** [7Yuliya/gamingActivity#1]
# Описание
При суммировании игрового времени игроков в методе getSumPlayedTime  программа возвращает ноль
# Локация дефекта
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/GameStore.java#L75-L78
# Шаги воспроизведения
1. Открыть код в  тесте shouldGetSumPlayedTime в классе GameStoreTest в IDEA
2. Запустить программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат* : Тест пройден

*Фактический результат* : Вывод сообщения о значении  игрового времени игроков равно 0
# Скриншоты
![2022-08-11](https://user-images.githubusercontent.com/106235296/184150343-c2dff390-06ab-4175-b943-975ca8e9260d.png)
![2022-08-11 (1)](https://user-images.githubusercontent.com/106235296/184150382-c33dd46d-c90a-4274-9daa-cf3adc000b36.png)

# Окружение
* **Операционная система:** Windows 10
* I**DE:** IntelliJ IDEA 2020.1.2 (Community Edition)
* **Java:** Eclipse Adoptium\jdk-11.0.14.101

**Comment by sapurina-t** [comment]
исправлено. метод не был реализован

<img width="1440" alt="Снимок экрана 2022-08-14 в 01 19 26" src="https://user-images.githubusercontent.com/102625576/184509540-4a47f667-617d-4646-93d2-3e64e023954f.png">
