### ISSUE TITLE
При добавлении игрового времени существующему игроку в методе addPlayTime время не суммируется

### ISSUE THREAD

**Issue by 7Yuliya** [7Yuliya/gamingActivity#10]
# Описание
При добавлении игрового времени существующему игроку в методе addPlayTime время не суммируется
# Локация дефекта
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/GameStore.java#L46-L52
# Шаги воспроизведения
1. Открыть код программы в тесте  shouldAddPlayedTimeOnePlayer в классе GameStoreTest в IDEA
2. Запустить программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат* : Тест пройден
*Фактический результат* : org.opentest4j.AssertionFailedError: 
Expected :1
Actual   :2
# Скриншоты
![2022-08-12](https://user-images.githubusercontent.com/106235296/184351769-7bc9c16a-3cf2-4d55-9e40-3c188f92e29c.png)
# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2020.1.2 (Community Edition)
* **Java:** Eclipse Adoptium\jdk-11.0.14.101

**Comment by sapurina-t** [comment]
исправлено. время не плюсовалось


<img width="1440" alt="Снимок экрана 2022-08-14 в 00 23 01" src="https://user-images.githubusercontent.com/102625576/184507945-4fbe1684-2675-4591-86b2-680d799bea73.png">
