### ISSUE TITLE
При добавлении нулевого времени игроков  игроку, играющему 1 час в методе getMostPlayer возвращается null

### ISSUE THREAD

**Issue by 7Yuliya** [7Yuliya/gamingActivity#11]
# Описание
При добавлении нулевого времени игроков  игроку, играющему 1 час в методе getMostPlayer возвращается null
# Локация дефекта
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/GameStore.java#L58-L69
# Шаги воспроизведения
1. Открыть код программы в  тесте shouldGetMostPlayerWithOneFromPlayersHours1  в классе GameStoreTest в IDEA
2. Запустить программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат* : Тест пройден

*Фактический результат* : org.opentest4j.AssertionFailedError: 
Expected :1
Actual   :null
# Скриншот
![2022-08-15 (7)](https://user-images.githubusercontent.com/106235296/184701675-b4a0fd45-71bb-49a7-b10b-856a89d1947c.png)
# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2020.1.2 (Community Edition)
* **Java:** Eclipse Adoptium\jdk-11.0.14.101

**Comment by sapurina-t** [comment]
исправлено. проблема была в инициализации переменной mostTime
<img width="1440" alt="Снимок экрана 2022-08-16 в 11 41 55" src="https://user-images.githubusercontent.com/102625576/184814652-ed21ddb0-5178-4001-acb2-13115d30b178.png">
