### ISSUE TITLE
метод play в классе Player принимает отрицательные значения игрового времени

### ISSUE THREAD

**Issue by sapurina-t** [7Yuliya/gamingActivity#12]
# Описание
метод принимает и обрабатывает отрацительные значения наравне с положительными

# Локализация дефекта 
https://github.com/7Yuliya/gamingActivity/blob/d8b14b034c6a65f88ad73c061288f5caa6f15f2f/src/main/java/ru/netology/Player.java#L45-L53

# Шаги воспроизведения
1. Открыть ветку player [код программы](https://github.com/7Yuliya/gamingActivity.git) как Maven проект в IDEA
1.  Запустить тест https://github.com/7Yuliya/gamingActivity/blob/894cd7a1f8ae67aab1d7a7779558a2cb2024b759/src/test/java/ru/netology/PlayerTest.java#L51-L72
1. Посмотреть на логи в консоли

*Ожидаемый результат:* 
Тест пройден

*Фактический результат:* 
Сообщение об ошибке org.opentest4j.AssertionFailedError: 
Expected :3
Actual   :2

# Скриншот
<img width="1440" alt="Снимок экрана 2022-08-16 в 10 12 58" src="https://user-images.githubusercontent.com/102625576/184805778-6e1be5e6-3cab-40a1-bf2d-0e91a782ad0e.png">

# Окружение
* **Операционная система:** MacOS Big Sur
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by 7Yuliya** [comment]
Предлагаю, вот такой тест для тестирования отрицательных значений:
![2022-08-16 (5)](https://user-images.githubusercontent.com/106235296/184827555-24155a95-c8d8-42dd-b986-957eb1d08931.png)
Так как в методе play используется метод addPlayTime ( public int play(Game game, int hours) {
        game.getStore().addPlayTime(name, hours);) :
![2022-08-16 (6)](https://user-images.githubusercontent.com/106235296/184831160-61599f0a-a2ff-42a2-98cf-b0562fd0a51f.png)
и если в методе addPlayTime  добавить исключение RuntimeException("Время не может быть отрицательным:" + hours):
![2022-08-16 (7)](https://user-images.githubusercontent.com/106235296/184831497-b6926c83-d135-4e95-aa13-8f91d05386ea.png)
Тогда и тест shouldSumGenreIfOneGame, к примеру, при добавлении отрицательного значения выбросит исключение: java.lang.RuntimeException: Время не может быть отрицательным:-3:
![2022-08-16 (8)](https://user-images.githubusercontent.com/106235296/184832781-7fd2b3d1-3e85-480c-afa8-da1c93f17bff.png)

**Comment by sapurina-t** [comment]
@7Yuliya, отличные прекрасные тесты

https://github.com/7Yuliya/gamingActivity/blob/894cd7a1f8ae67aab1d7a7779558a2cb2024b759/src/main/java/ru/netology/Player.java#L38-L53

но описание к методу говорит, что исключение нужно выкидывать при неустановленной игре. при других случаях - нет такой задачи

**Comment by 7Yuliya** [comment]
Вопрос открыт. Корректировки в проект не стали добавлять
