### ISSUE TITLE
метод sumGenre в классе Player не суммирует время игры по одному жанру

### ISSUE THREAD

**Issue by sapurina-t** [7Yuliya/gamingActivity#2]
# Описание
Тест вызывает метод и возвращает 0

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/7Yuliya/gamingActivity.git) как Maven проект в IDEA
1.  Запустить тест https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/test/java/ru/netology/PlayerTest.java#L10
1. Посмотреть на логи в консоли

*Ожидаемый результат:* 
Тест пройдет

*Фактический результат:* 
Сообщение об ошибке org.opentest4j.AssertionFailedError: 
Expected :3
Actual   :0

<img width="1033" alt="Снимок экрана 2022-08-11 в 17 20 39" src="https://user-images.githubusercontent.com/102625576/184132159-4303dfe7-3aca-4cf0-a257-c55d315ac3fb.png">

# Окружение
* **Операционная система:** MacOS Big Sur
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by sapurina-t** [comment]
#Локализация дефекта
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/Player.java#L56-L66

**Comment by 7Yuliya** [comment]
Исправлено. В методе play добавлены hours
![2022-08-14](https://user-images.githubusercontent.com/106235296/184533223-07bb7812-e3a5-4f98-81c4-34f64ea2d3af.png)
![2022-08-14 (1)](https://user-images.githubusercontent.com/106235296/184533227-c6dde240-bf44-4074-8a05-19883649d0f2.png)
