### ISSUE TITLE
При добавлении игры  в каталог  программа возвращает  false в методе containsGame

### ISSUE THREAD

**Issue by 7Yuliya** [7Yuliya/gamingActivity#3]
# Описание
 Программа не находит добавленную в каталог игру и возвращает  false в методе containsGame
# Локация дефекта
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/GameStore.java#L32-L39
# Шаги воспроизведения
1. Открыть код программы в тесте  shouldAddGame в классе GameStoreTest  в IDEA
2. Запустить программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат* : Тест пройден

*Фактический результат* : false
# Скриншот
![2022-08-11 (2)](https://user-images.githubusercontent.com/106235296/184166425-16c3028f-9a51-4775-9b1d-5fe63cded9ca.png)
# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2020.1.2 (Community Edition)
* **Java:** Eclipse Adoptium\jdk-11.0.14.101

**Comment by sapurina-t** [comment]
ошибка в инициализации и в теле цикла. будет исправлено


<img width="1440" alt="Снимок экрана 2022-08-13 в 23 28 39" src="https://user-images.githubusercontent.com/102625576/184506360-220f625a-d0c4-4668-9c85-6d1dc08443ea.png">
