### ISSUE TITLE
метод play в классе Player не выкидывает ошибку RuntimeException при обращении к неустановленной игре

### ISSUE THREAD

**Issue by sapurina-t** [7Yuliya/gamingActivity#4]
# Описание
метод не выводит ошибку типа RuntimeException

# Локализация дефекта 
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/Player.java#L42-L50

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/7Yuliya/gamingActivity.git) как Maven проект в IDEA
1.  Запустить тест https://github.com/7Yuliya/gamingActivity/blob/f9d24f560c207a65e83c594be901a11008a4c7c8/src/test/java/ru/netology/PlayerTest.java#L52-L65
1. Посмотреть на логи в консоли

*Ожидаемый результат:* 
Тест пройден

*Фактический результат:* 
Сообщение об ошибке org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
<img width="1360" alt="Снимок экрана 2022-08-11 в 23 13 46" src="https://user-images.githubusercontent.com/102625576/184218098-3b0289fb-3ef2-4711-aacb-b30187519e7a.png">

# Окружение
* **Операционная система:** MacOS Big Sur
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by 7Yuliya** [comment]
Исправлено. В методе play добавлено исключение RuntimeException, если игра не была установлена
![2022-08-14 (2)](https://user-images.githubusercontent.com/106235296/184533600-35f28967-261e-4fc5-88a6-190d22db0422.png)
![2022-08-14 (3)](https://user-images.githubusercontent.com/106235296/184533613-b4ba932f-771d-4b45-9069-334044d93f17.png)
