### ISSUE TITLE
метод sumGenre в классе Player не суммирует время нескольких игр игрока по одному жанру

### ISSUE THREAD

**Issue by sapurina-t** [7Yuliya/gamingActivity#5]
# Описание
Тест вызывает метод и возвращает 0

# Локализация дефекта 
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/Player.java#L56-L66

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/7Yuliya/gamingActivity.git) как Maven проект в IDEA
1.  Запустить тест https://github.com/7Yuliya/gamingActivity/blob/f9d24f560c207a65e83c594be901a11008a4c7c8/src/test/java/ru/netology/PlayerTest.java#L29-L48
1. Посмотреть на логи в консоли

*Ожидаемый результат:* 
Тест пройден

*Фактический результат:* 
org.opentest4j.AssertionFailedError: 
Expected :6
Actual   :0

# Скриншот
<img width="1440" alt="Снимок экрана 2022-08-11 в 23 41 16" src="https://user-images.githubusercontent.com/102625576/184217739-7e47074a-a7a7-435a-a09c-a67513bf6007.png">

# Окружение
* **Операционная система:** MacOS Big Sur
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by 7Yuliya** [comment]
Исправлено. В методе sumGenre удалены строки
 } else {
sum = 0;
![2022-08-14 (4)](https://user-images.githubusercontent.com/106235296/184534073-51506a89-0203-43b8-aa31-f3666670f42b.png)
![2022-08-14 (6)](https://user-images.githubusercontent.com/106235296/184534136-de2022ee-1fac-4994-911c-5adca6fdc961.png)
