### ISSUE TITLE
метод installGame сбрасывает показатель времени при повторном добавлении игры

### ISSUE THREAD

**Issue by sapurina-t** [7Yuliya/gamingActivity#6]
# Описание
метод обнуляет `playedTime`, не учитывает время игры

# Локализация дефекта 
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/Player.java#L31-L33

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/7Yuliya/gamingActivity.git) как Maven проект в IDEA
1.  Запустить тест https://github.com/7Yuliya/gamingActivity/blob/f9d24f560c207a65e83c594be901a11008a4c7c8/src/test/java/ru/netology/PlayerTest.java#L70-L82
1. Посмотреть на логи в консоли

*Ожидаемый результат:* 
Тест пройден

*Фактический результат:* 
Сообщение об ошибке org.opentest4j.AssertionFailedError: 
Expected :5
Actual   :0

# Скриншот
<img width="1440" alt="Снимок экрана 2022-08-11 в 23 52 32" src="https://user-images.githubusercontent.com/102625576/184217365-ed8db6e8-87fd-469f-9084-18c9957ed400.png">

# Окружение
* **Операционная система:** MacOS Big Sur
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by 7Yuliya** [comment]
Исправлено. В метод installGame добавлено:
{
        if (playedTime.containsKey(game)) {
            playedTime.put(game, playedTime.get(game) );
        } else {playedTime.put(game, 0);
    }
![2022-08-14 (10)](https://user-images.githubusercontent.com/106235296/184536234-cdb83ead-4317-49ef-97c3-64f841724d5e.png)
![2022-08-14 (11)](https://user-images.githubusercontent.com/106235296/184536244-1fbb38b1-6169-4bbd-bbe2-684a8361ad75.png)
