### ISSUE TITLE
метод mostPlayerByGenre не возвращает игру в которую играли дольше всего про поиске по жанру

### ISSUE THREAD

**Issue by sapurina-t** [7Yuliya/gamingActivity#7]
# Описание
метод возвращает null

# Локализация дефекта 
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/Player.java#L72-L74

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/7Yuliya/gamingActivity.git) как Maven проект в IDEA
1.  Запустить тест https://github.com/7Yuliya/gamingActivity/blob/f9d24f560c207a65e83c594be901a11008a4c7c8/src/test/java/ru/netology/PlayerTest.java#L87-L104
1. Посмотреть на логи в консоли

*Ожидаемый результат:* 
Тест пройден

*Фактический результат:* 
Сообщение об ошибке org.opentest4j.AssertionFailedError: 
Expected :ru.netology.Game@89bc38f7
Actual   :null

# Скриншот
<img width="1440" alt="Снимок экрана 2022-08-12 в 00 01 59" src="https://user-images.githubusercontent.com/102625576/184219203-6f420b64-49be-4d4b-b328-f3f5defce111.png">

# Окружение
* **Операционная система:** MacOS Big Sur
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by 7Yuliya** [comment]
Исправлено. Дописан нереализованный метод mostPlayerByGenre
![2022-08-14 (7)](https://user-images.githubusercontent.com/106235296/184535312-76845418-d7bc-484e-a12e-9ebf1e2fc543.png)
![2022-08-14 (8)](https://user-images.githubusercontent.com/106235296/184535324-edcd8a25-f7fa-420a-adee-b46217cbe7b4.png)
