### ISSUE TITLE
метод mostPlayerByGenre возвращает null без проверки запускалась ли игра

### ISSUE THREAD

**Issue by sapurina-t** [7Yuliya/gamingActivity#8]
# Описание
метод без проверки выводит null

# Локализация дефекта 
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/Player.java#L72-L74

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/7Yuliya/gamingActivity.git) как Maven проект в IDEA
1.  Запустить тест https://github.com/7Yuliya/gamingActivity/blob/f9d24f560c207a65e83c594be901a11008a4c7c8/src/test/java/ru/netology/PlayerTest.java#L109-L125
1. Посмотреть на логи в консоли

*Ожидаемый результат:* 
Тест пройден после проверки методом, что игра не запускалась

*Фактический результат:* 
Тест пройден, метод просто возвращает null

# Скриншот
<img width="1440" alt="Снимок экрана 2022-08-12 в 00 13 03" src="https://user-images.githubusercontent.com/102625576/184221174-79890aa8-c201-47ff-8254-78e334ff793f.png">
<img width="1440" alt="Снимок экрана 2022-08-12 в 00 12 27" src="https://user-images.githubusercontent.com/102625576/184221208-c04e8860-7121-4f33-82c4-702f87dfb1a2.png">

# Окружение
* **Операционная система:** MacOS Big Sur
* **IDE:** IntelliJ IDEA 2022.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by 7Yuliya** [comment]
Исправлено. Дописан нереализованный метод
![2022-08-14 (7)](https://user-images.githubusercontent.com/106235296/184535419-2a781274-668c-4832-ba5b-b3cb6e435009.png)
![2022-08-14 (9)](https://user-images.githubusercontent.com/106235296/184535432-9c3014a4-9ad9-4878-b0ea-00d03910dd38.png)
