### ISSUE TITLE
Метод addPlayTime принимает отрицательные и нулевые значения

### ISSUE THREAD

**Issue by 7Yuliya** [7Yuliya/gamingActivity#9]
# Описание
Метод addPlayTime принимает отрицательные и нулевые значения
# Локация дефекта
https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения
1. Открыть код программы в тесте shouldAddPlayedTimeNegativeException в  классе GameStoreTest в IDEA
2. Запустить программу
3. Посмотреть на вывод в консоли

*Ожидаемый результат* : Программа выбросит исключение

*Фактический результат* : org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.
# Скриншоты
![2022-08-11 (6)](https://user-images.githubusercontent.com/106235296/184252811-27ba6caa-4d92-4804-9606-15d0f706b853.png)
![2022-08-11 (7)](https://user-images.githubusercontent.com/106235296/184252860-29fe1ebb-18cb-4b9d-ad9a-d022897f958d.png)
# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2020.1.2 (Community Edition)
* **Java:** Eclipse Adoptium\jdk-11.0.14.101

**Comment by sapurina-t** [comment]
руководствуясь здравым смыслом, понимаю, что метод не должен принимать нулевые и отрицательные значения. но в описании к методу ничего не сказано о том, что он должен выкидывать ошибку

https://github.com/7Yuliya/gamingActivity/blob/a45c8438dcd9fefe4d8e060c0c26fa1add406dfe/src/main/java/ru/netology/GameStore.java#L41-L52

**Comment by sapurina-t** [comment]
пофиксила в предыдущем [коммите](https://github.com/7Yuliya/gamingActivity/commit/c4e15d16ba7de857cf346c44cfa2a2c0acc16985). 
https://github.com/7Yuliya/gamingActivity/blob/c4e15d16ba7de857cf346c44cfa2a2c0acc16985/src/main/java/ru/netology/GameStore.java#L48-L56
поставила, чтобы метод принимал значение больше 0. если будем выкидывать исключение, тест 
https://github.com/7Yuliya/gamingActivity/blob/c4e15d16ba7de857cf346c44cfa2a2c0acc16985/src/test/java/ru/netology/GameStoreTest.java#L105-L119
будет падать, не просчитывая положительные часы игры

потребуется написать дополнительный тест на метод
<img width="1440" alt="Снимок экрана 2022-08-14 в 21 44 35" src="https://user-images.githubusercontent.com/102625576/184546898-9efd3978-a60e-409c-bc79-1aba501bf88a.png">

**Comment by sapurina-t** [comment]
0 оставила. он не влияет на значение суммы

**Comment by 7Yuliya** [comment]
Предлагаю сделать вот так:
![2022-08-15 (3)](https://user-images.githubusercontent.com/106235296/184619946-46e76383-fb26-4e8f-a8ab-cb089efc4f04.png)
Тогда тесты пройдут:
![2022-08-15 (5)](https://user-images.githubusercontent.com/106235296/184620060-2b21fa3d-1f5c-409f-a8af-bbf7bb78b43c.png)
![2022-08-15 (4)](https://user-images.githubusercontent.com/106235296/184620349-35f6d144-a9e7-463c-adfe-c8247edca1e8.png)
А тест с отрицательным значением выбросит исключение RuntimeException("Время не может быть отрицательным")
и чтобы сборка не упала не будем тест добавлять
![2022-08-15 (6)](https://user-images.githubusercontent.com/106235296/184620729-d6218db3-a14e-4f6b-950e-5e593cca6cb6.png)

**Comment by sapurina-t** [comment]
https://github.com/7Yuliya/gamingActivity/blob/d75ed84ddcc715b6ae4300dd6dbf0186876d7baf/src/main/java/ru/netology/GameStore.java#L41-L45

опираясь на описание к методу, предлагаю не требовать от него выкидывать исключение и убрать тесты, которые просят этого
